### ISSUE TITLE
name 'count' is not defined报错帮看下

### ISSUE THREAD

**Issue by zhanghaobucunzai** [tobran/DF-GAN#11]
[1/1][365/368] Loss_D: 1.329 Loss_G 1.297
[1/1][366/368] Loss_D: 1.162 Loss_G 3.206
[1/1][367/368] Loss_D: 1.162 Loss_G 2.319
Traceback (most recent call last):
  File "main.py", line 273, in <module>
    count = train(dataloader,netG,netD,text_encoder,optimizerG,optimizerD, state_epoch,batch_size,device)
  File "main.py", line 179, in train
    return count
NameError: name 'count' is not defined

**Comment by rishi-wqd190004** [comment]
@zhanghaobucunzai hi wanted to know did you also got the similar error as [RNN_ENCODER](https://github.com/tobran/DF-GAN/issues/12#issue-948945516) too. If so could you share some insights on why its happening.

**Comment by YGfun** [comment]
@zhanghaobucunzai you cab just delete it.
